USE [master]
GO

/****** Object:  Database [CustomerDb]    Script Date: 4/13/2019 8:07:36 PM ******/
CREATE DATABASE [CustomerDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CustomerDb', FILENAME = N'S:\MSSQL14.MSSQLSERVER\MSSQL\DATA\CustomerDb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CustomerDb_log', FILENAME = N'S:\MSSQL14.MSSQLSERVER\MSSQL\DATA\CustomerDb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [CustomerDb] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CustomerDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CustomerDb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CustomerDb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CustomerDb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CustomerDb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CustomerDb] SET ARITHABORT OFF 
GO

ALTER DATABASE [CustomerDb] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CustomerDb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CustomerDb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CustomerDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CustomerDb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CustomerDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CustomerDb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CustomerDb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CustomerDb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CustomerDb] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CustomerDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CustomerDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CustomerDb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CustomerDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CustomerDb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CustomerDb] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CustomerDb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CustomerDb] SET RECOVERY FULL 
GO

ALTER DATABASE [CustomerDb] SET  MULTI_USER 
GO

ALTER DATABASE [CustomerDb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CustomerDb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CustomerDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CustomerDb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [CustomerDb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CustomerDb] SET QUERY_STORE = OFF
GO

ALTER DATABASE [CustomerDb] SET  READ_WRITE 
GO


USE [CustomerDb]
GO

/****** Object:  Table [dbo].[Customer]    Script Date: 4/13/2019 8:07:36 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Customer](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](100) NOT NULL,
	[Address] [nvarchar](200) NOT NULL,
	[Mobile] [nvarchar](15) NOT NULL,
	[BirthDate] [datetime] NOT NULL,
	[Email] [nvarchar](20) NOT NULL,
 CONSTRAINT [PK_Customer] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


